/**
 * @fileoverview Defines the IAdmin interface for admin data.
 * @version 1.0.0
 * @module adminInterface
 */

import { Optional } from 'sequelize';

/**
 * Interface representing the attributes of an admin.
 */
export interface IAdmin {
  id?: number;
  firstName?: string;
  lastName?: string;
  userId?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Interface for creating a new admin (excluding autogenerated fields).
 */
export type IAdminCreation = Optional<IAdmin, 'id' | 'createdAt' | 'updatedAt'>;
