/**
 * @fileoverview Defines the ICompany interface for company data.
 * @version 1.0.0
 * @module companyInterface
 */

import { Optional } from 'sequelize';

/**
 * Interface representing the attributes of a company.
 */
export interface IRecruiter {
  id?: number;
  name?: string;
  industry?: string;
  websiteUrl?: string;
  location?: string;
  description?: string;
  size?: number;
  foundedIn?: number;
  isVerified?: boolean;
  userId?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Interface for creating a new company (excluding autogenerated fields).
 */
export type IRecruiterCreation = Optional<
  IRecruiter,
  'id' | 'createdAt' | 'updatedAt'
>;
